type Address = `0x${string}`;

export type AddressCategory =
  | "bridge"
  | "dex"
  | "lending"
  | "stablecoin_issuer"
  | "system"
  | "unidentified";

export type AddressCountingPolicy = "boundary" | "discovery_source" | "ignore" | "internal";

export type AddressConfidence = "candidate" | "high" | "medium";

export type AddressLabel = {
  address: Address;
  attributionGroup: string;
  category: AddressCategory;
  confidence: AddressConfidence;
  countingPolicy: AddressCountingPolicy;
  entityId: string;
  entityName: string;
  label: string;
  role: string;
};

export type DiscoveredAddressLabelInput = Pick<
  AddressLabel,
  | "address"
  | "attributionGroup"
  | "category"
  | "confidence"
  | "countingPolicy"
  | "entityId"
  | "entityName"
  | "label"
  | "role"
>;

const baseAddressLabels = [
  {
    address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    attributionGroup: "circle-usdc",
    category: "stablecoin_issuer",
    confidence: "high",
    countingPolicy: "ignore",
    entityId: "circle",
    entityName: "Circle",
    label: "USDC token",
    role: "token",
  },
  {
    address: "0x4200000000000000000000000000000000000006",
    attributionGroup: "base-system",
    category: "system",
    confidence: "high",
    countingPolicy: "ignore",
    entityId: "base",
    entityName: "Base",
    label: "WETH9 predeploy",
    role: "predeploy",
  },
  {
    address: "0x4200000000000000000000000000000000000007",
    attributionGroup: "base-native-bridge",
    category: "bridge",
    confidence: "high",
    countingPolicy: "internal",
    entityId: "base-native-bridge",
    entityName: "Base Native Bridge",
    label: "L2CrossDomainMessenger",
    role: "messenger",
  },
  {
    address: "0x4200000000000000000000000000000000000010",
    attributionGroup: "base-native-bridge",
    category: "bridge",
    confidence: "high",
    countingPolicy: "boundary",
    entityId: "base-native-bridge",
    entityName: "Base Native Bridge",
    label: "L2StandardBridge",
    role: "bridge",
  },
  {
    address: "0x4200000000000000000000000000000000000016",
    attributionGroup: "base-native-bridge",
    category: "bridge",
    confidence: "high",
    countingPolicy: "internal",
    entityId: "base-native-bridge",
    entityName: "Base Native Bridge",
    label: "L2ToL1MessagePasser",
    role: "message_passer",
  },
  {
    address: "0x28b5a0e9C621a5BadaA536219b3a228C8168cf5d",
    attributionGroup: "circle-cctp",
    category: "bridge",
    confidence: "high",
    countingPolicy: "boundary",
    entityId: "circle-cctp",
    entityName: "Circle CCTP",
    label: "TokenMessengerV2",
    role: "token_messenger",
  },
  {
    address: "0x81D40F21F12A8F0E3252Bccb954D722d4c464B64",
    attributionGroup: "circle-cctp",
    category: "bridge",
    confidence: "high",
    countingPolicy: "internal",
    entityId: "circle-cctp",
    entityName: "Circle CCTP",
    label: "MessageTransmitterV2",
    role: "message_transmitter",
  },
  {
    address: "0x000000000022D473030F116dDEE9F6B43aC78BA3",
    attributionGroup: "uniswap-v3",
    category: "dex",
    confidence: "high",
    countingPolicy: "internal",
    entityId: "uniswap-v3",
    entityName: "Uniswap V3",
    label: "Permit2",
    role: "permit",
  },
  {
    address: "0x198EF79F1F515F02dFE9e3115eD9fC07183f02fC",
    attributionGroup: "uniswap-v3",
    category: "dex",
    confidence: "high",
    countingPolicy: "boundary",
    entityId: "uniswap-v3",
    entityName: "Uniswap V3",
    label: "UniversalRouter",
    role: "router",
  },
  {
    address: "0x33128a8fC17869897dcE68Ed026d694621f6FDfD",
    attributionGroup: "uniswap-v3",
    category: "dex",
    confidence: "high",
    countingPolicy: "discovery_source",
    entityId: "uniswap-v3",
    entityName: "Uniswap V3",
    label: "Factory",
    role: "factory",
  },
  {
    address: "0x03a520b32C04BF3bEEf7BEb72E919cf822Ed34f1",
    attributionGroup: "uniswap-v3",
    category: "dex",
    confidence: "high",
    countingPolicy: "internal",
    entityId: "uniswap-v3",
    entityName: "Uniswap V3",
    label: "NonfungiblePositionManager",
    role: "position_manager",
  },
  {
    address: "0x2626664c2603336E57B271c5C0b26F421741e481",
    attributionGroup: "uniswap-v3",
    category: "dex",
    confidence: "high",
    countingPolicy: "boundary",
    entityId: "uniswap-v3",
    entityName: "Uniswap V3",
    label: "SwapRouter02",
    role: "router",
  },
  {
    address: "0x3d4e44Eb1374240CE5F1B871ab261CD16335B76a",
    attributionGroup: "uniswap-v3",
    category: "dex",
    confidence: "high",
    countingPolicy: "ignore",
    entityId: "uniswap-v3",
    entityName: "Uniswap V3",
    label: "QuoterV2",
    role: "quoter",
  },
  {
    address: "0xcF77a3Ba9A5CA399B7c97c74d54e5b1Beb874E43",
    attributionGroup: "aerodrome",
    category: "dex",
    confidence: "high",
    countingPolicy: "boundary",
    entityId: "aerodrome",
    entityName: "Aerodrome",
    label: "Router",
    role: "router",
  },
  {
    address: "0x420DD381b31aEf6683db6B902084cB0FFECe40Da",
    attributionGroup: "aerodrome",
    category: "dex",
    confidence: "high",
    countingPolicy: "discovery_source",
    entityId: "aerodrome",
    entityName: "Aerodrome",
    label: "PoolFactory",
    role: "factory",
  },
  {
    address: "0x5e7BB104d84C7CB9b682AAC2F3D509f5F406809A",
    attributionGroup: "aerodrome",
    category: "dex",
    confidence: "high",
    countingPolicy: "discovery_source",
    entityId: "aerodrome",
    entityName: "Aerodrome",
    label: "SlipStream",
    role: "factory",
  },
  {
    address: "0xeC8E5342B19977B4eF8892e02D8DAEcfa1315831",
    attributionGroup: "aerodrome",
    category: "dex",
    confidence: "high",
    countingPolicy: "discovery_source",
    entityId: "aerodrome",
    entityName: "Aerodrome",
    label: "SlipStream Pool Factory",
    role: "factory",
  },
  {
    address: "0x5C3F18F06CC09CA1910767A34a20F771039E37C0",
    attributionGroup: "aerodrome",
    category: "dex",
    confidence: "high",
    countingPolicy: "discovery_source",
    entityId: "aerodrome",
    entityName: "Aerodrome",
    label: "FactoryRegistry",
    role: "factory_registry",
  },
  {
    address: "0x16613524e02ad97eDfeF371bC883F2F5d6C480A5",
    attributionGroup: "aerodrome",
    category: "dex",
    confidence: "high",
    countingPolicy: "internal",
    entityId: "aerodrome",
    entityName: "Aerodrome",
    label: "Voter",
    role: "voter",
  },
  {
    address: "0x940181a94A35A4569E4529A3CDfB74e38FD98631",
    attributionGroup: "aerodrome",
    category: "dex",
    confidence: "high",
    countingPolicy: "ignore",
    entityId: "aerodrome",
    entityName: "Aerodrome",
    label: "AERO token",
    role: "token",
  },
  {
    address: "0xA238Dd80C259a72e81d7e4664a9801593F98d1c5",
    attributionGroup: "aave-v3",
    category: "lending",
    confidence: "high",
    countingPolicy: "boundary",
    entityId: "aave-v3",
    entityName: "Aave V3",
    label: "Pool",
    role: "pool",
  },
  {
    address: "0xe20fCBdBfFC4Dd138cE8b2E6FBb6CB49777ad64D",
    attributionGroup: "aave-v3",
    category: "lending",
    confidence: "high",
    countingPolicy: "discovery_source",
    entityId: "aave-v3",
    entityName: "Aave V3",
    label: "PoolAddressesProvider",
    role: "address_provider",
  },
  {
    address: "0xa0d9C1E9E48Ca30c8d8C3B5D69FF5dc1f6DFfC24",
    attributionGroup: "aave-v3",
    category: "lending",
    confidence: "medium",
    countingPolicy: "boundary",
    entityId: "aave-v3",
    entityName: "Aave V3",
    label: "WrappedTokenGatewayV3",
    role: "gateway",
  },
  {
    address: "0xb125E6687d4313864e53df431d5425969c15Eb2F",
    attributionGroup: "compound-v3",
    category: "lending",
    confidence: "high",
    countingPolicy: "boundary",
    entityId: "compound-v3",
    entityName: "Compound V3",
    label: "cUSDCv3 / Comet proxy",
    role: "market",
  },
  {
    address: "0x45939657d1CA34A8FA39A924B71D28Fe8431e581",
    attributionGroup: "compound-v3",
    category: "lending",
    confidence: "high",
    countingPolicy: "discovery_source",
    entityId: "compound-v3",
    entityName: "Compound V3",
    label: "Configurator",
    role: "configurator",
  },
  {
    address: "0x123964802e6ABabBE1Bc9547D72Ef1B69B00A6b1",
    attributionGroup: "compound-v3",
    category: "lending",
    confidence: "high",
    countingPolicy: "internal",
    entityId: "compound-v3",
    entityName: "Compound V3",
    label: "Rewards",
    role: "rewards",
  },
  {
    address: "0x78D0677032A35c63D142a48A2037048871212a8C",
    attributionGroup: "compound-v3",
    category: "lending",
    confidence: "high",
    countingPolicy: "boundary",
    entityId: "compound-v3",
    entityName: "Compound V3",
    label: "Bulker",
    role: "bulker",
  },
  {
    address: "0xBBBBBbbBBb9cC5e90e3b3Af64bdAF62C37EEFFCb",
    attributionGroup: "morpho-blue",
    category: "lending",
    confidence: "medium",
    countingPolicy: "boundary",
    entityId: "morpho-blue",
    entityName: "Morpho Blue",
    label: "Morpho Blue",
    role: "core",
  },
  {
    address: "0x46415998764C29aB2a25CbeA6254146D50D22687",
    attributionGroup: "morpho-blue",
    category: "lending",
    confidence: "medium",
    countingPolicy: "internal",
    entityId: "morpho-blue",
    entityName: "Morpho Blue",
    label: "AdaptiveCurveIRM",
    role: "interest_rate_model",
  },
  {
    address: "0x2DC205F24BCb6B311E5cdf0745B0741648Aebd3d",
    attributionGroup: "morpho-blue",
    category: "lending",
    confidence: "medium",
    countingPolicy: "discovery_source",
    entityId: "morpho-blue",
    entityName: "Morpho Blue",
    label: "Oracle Factory",
    role: "oracle_factory",
  },
  {
    address: "0xA9c3D3a366466Fa809d1Ae982Fb2c46E5fC41101",
    attributionGroup: "morpho-blue",
    category: "lending",
    confidence: "medium",
    countingPolicy: "discovery_source",
    entityId: "morpho-blue",
    entityName: "Morpho Blue",
    label: "MetaMorpho Vault Factory",
    role: "vault_factory",
  },
  {
    address: "0xA090dD1a701408Df1d4d0B85b716c87565f90467",
    attributionGroup: "morpho-blue",
    category: "lending",
    confidence: "medium",
    countingPolicy: "internal",
    entityId: "morpho-blue",
    entityName: "Morpho Blue",
    label: "PublicAllocator",
    role: "allocator",
  },
  {
    address: "0x0BFbCF9fa4f9C56B0F40a671Ad40E0805A091865",
    attributionGroup: "pancakeswap-v3",
    category: "dex",
    confidence: "high",
    countingPolicy: "discovery_source",
    entityId: "pancakeswap-v3",
    entityName: "PancakeSwap V3",
    label: "PancakeV3Factory",
    role: "factory",
  },
  {
    address: "0x41ff9AA7e16B8B1a8a8dc4f0eFacd93D02d071c9",
    attributionGroup: "pancakeswap-v3",
    category: "dex",
    confidence: "high",
    countingPolicy: "internal",
    entityId: "pancakeswap-v3",
    entityName: "PancakeSwap V3",
    label: "PancakeV3PoolDeployer",
    role: "pool_deployer",
  },
  {
    address: "0x1b81D678ffb9C0263b24A97847620C99d213eB14",
    attributionGroup: "pancakeswap-v3",
    category: "dex",
    confidence: "high",
    countingPolicy: "boundary",
    entityId: "pancakeswap-v3",
    entityName: "PancakeSwap V3",
    label: "SwapRouter",
    role: "router",
  },
  {
    address: "0x46A15B0b27311cedF172AB29E4f4766fbE7F4364",
    attributionGroup: "pancakeswap-v3",
    category: "dex",
    confidence: "high",
    countingPolicy: "internal",
    entityId: "pancakeswap-v3",
    entityName: "PancakeSwap V3",
    label: "NonfungiblePositionManager",
    role: "position_manager",
  },
  {
    address: "0xB048Bbc1Ee6b733FFfCFb9e9CeF7375518e25997",
    attributionGroup: "pancakeswap-v3",
    category: "dex",
    confidence: "high",
    countingPolicy: "ignore",
    entityId: "pancakeswap-v3",
    entityName: "PancakeSwap V3",
    label: "QuoterV2",
    role: "quoter",
  },
  {
    address: "0x09aea4b2242abC8bb4BB78D537A67a245A7bEC64",
    attributionGroup: "across",
    category: "bridge",
    confidence: "high",
    countingPolicy: "boundary",
    entityId: "across",
    entityName: "Across",
    label: "SpokePool",
    role: "pool",
  },
  {
    address: "0x10D8b8DaA26d307489803e10477De69C0492B610",
    attributionGroup: "across",
    category: "bridge",
    confidence: "high",
    countingPolicy: "boundary",
    entityId: "across",
    entityName: "Across",
    label: "SpokePoolPeriphery",
    role: "periphery",
  },
] as const satisfies readonly AddressLabel[];

const addressLabelsByAddress = new Map(
  baseAddressLabels.map((label) => [label.address.toLowerCase(), label]),
);

export const getBaseAddressLabel = (address: Address) =>
  addressLabelsByAddress.get(address.toLowerCase());

export const isFlowBoundaryLabel = (label: Pick<AddressLabel, "countingPolicy"> | undefined) =>
  label?.countingPolicy === "boundary";

export { baseAddressLabels };
